---
version: '2'
services:
  kibana:
    build:
      context: build/kibana
      args:
        KIBANA_VERSION: "${KIBANA_VERSION}"
    image: kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: container-registry.elastic.co/elasticsearch/elasticsearch:${KIBANA_VERSION}

  tester:
    build:
      context: build/python
    links:
      - kibana
    volumes:
      - ./tests:/tmp/tests
