---
version: '2'
services:
  kibana:
    build:
      context: build/kibana
      args:
        KIBANA_VERSION: "${KIBANA_VERSION}"
    image: kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601

    # Configure certificate and key files to enable SSL. The certificate
    # provided in the example is self-signed, and thus insecure. It should
    # only be used for experimentation, never in production.
    # 
    # environment:
    #   - SERVER_SSL_CERT=/opt/kibana/config/kibana.example.org.crt
    #   - SERVER_SSL_KEY=/opt/kibana/config/kibana.example.org.key

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${KIBANA_VERSION}

  tester:
    build:
      context: build/python
    links:
      - kibana
    volumes:
      - ./tests:/tmp/tests
